package ORM;
// Generated 11 nov. 2020 18:30:50 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private String dni;
	private String nomEmp;
	private Set proyectos = new HashSet(0);
	private Set asigProyectos = new HashSet(0);
	private DatosProf datosProf;

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, Set proyectos, Set asigProyectos, DatosProf datosProf) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.proyectos = proyectos;
		this.asigProyectos = asigProyectos;
		this.datosProf = datosProf;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

	public Set getAsigProyectos() {
		return this.asigProyectos;
	}

	public void setAsigProyectos(Set asigProyectos) {
		this.asigProyectos = asigProyectos;
	}

	public DatosProf getDatosProf() {
		return this.datosProf;
	}

	public void setDatosProf(DatosProf datosProf) {
		this.datosProf = datosProf;
	}

}
